# Project: AG_2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = AG_2.o
LINKOBJ  = AG_2.o
LIBS     = -L"B:/Desktop/Dev-C/Dev-Cpp/MinGW64/lib" -L"B:/Desktop/Dev-C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"B:/Desktop/Dev-C/Dev-Cpp/MinGW64/include" -I"B:/Desktop/Dev-C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"B:/Desktop/Dev-C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"B:/Desktop/Dev-C/Dev-Cpp/MinGW64/include" -I"B:/Desktop/Dev-C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"B:/Desktop/Dev-C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"B:/Desktop/Dev-C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = AG_2.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

AG_2.o: AG_2.c
	$(CC) -c AG_2.c -o AG_2.o $(CFLAGS)
